2019-03-05 13:36:03 [main] t3.utils.connman.c.Ck()
ERROR: Unable to load color preferences.: java.io.FileNotFoundException: /Users/robcrock/.3T/roaming/color_preferences.dat (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at t3.utils.connman.c.Ck(ColoringPreferenceStore.java:157)
	at t3.utils.connman.c.<clinit>(ColoringPreferenceStore.java:71)
	at t3.utils.cn.a(XStreamFactory.java:82)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at t3.utils.cn.zo(XStreamFactory.java:82)
	at t3.utils.cn.toXML(XStreamFactory.java:92)
	at t3.utils.s.a.Cj(AppProperties.java:1483)
	at t3.utils.s.a.ak(AppProperties.java:1445)
	at t3.utils.s.a.ajj(AppProperties.java:1380)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)
2019-03-05 13:36:20 [3T::Runner::initToolExecutablePaths] t3.utils.s.n.ly()
ERROR: Couldn't unpack bundled third-party resource: libeay32.dll
2019-03-05 13:36:20 [3T::Runner::initToolExecutablePaths] t3.utils.s.n.ly()
ERROR: Couldn't unpack bundled third-party resource: msvcp140.dll
2019-03-05 13:36:20 [3T::Runner::initToolExecutablePaths] t3.utils.s.n.ly()
ERROR: Couldn't unpack bundled third-party resource: ssleay32.dll
2019-03-05 13:36:20 [3T::Runner::initToolExecutablePaths] t3.utils.s.n.ly()
ERROR: Couldn't unpack bundled third-party resource: vcruntime140.dll
2019-03-05 13:36:20 [main] t3.utils.s.x.akU()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at t3.utils.s.x.akU(ManagedPropertyStore.java:228)
	at t3.utils.s.ah.get(PropertyStore.java:248)
	at t3.utils.s.ah.get(PropertyStore.java:245)
	at t3.utils.s.ad.a(PropertyStore.java:64)
	at t3.utils.s.ac.a(PropertyStore.java:245)
	at t3.utils.s.x.read(ManagedPropertyStore.java:224)
	at t3.utils.s.x.a(ManagedPropertyStore.java:128)
	at t3.utils.s.x.lB(ManagedPropertyStore.java:87)
	at t3.utils.s.j.<clinit>(DefaultTrustedPropertyStore.java:16)
	at t3.utils.connman.ed.aP(MongoConnectionInfoRestrictions.java:76)
	at t3.utils.connman.ed.Fm(MongoConnectionInfoRestrictions.java:147)
	at t3.utils.connman.ed.<init>(MongoConnectionInfoRestrictions.java:43)
	at t3.utils.connman.bu.<init>(ConnectionManager.java:89)
	at t3.dataman.mongodb.app.a.<init>(AppController.java:123)
	at t3.dataman.mongodb.app.ae.main(AppRunner.java:84)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)
2019-03-05 13:42:59 [main] t3.utils.connman.ej.a()
ERROR: Update is ProgressUpdate: Connecting to 172.31.33.227:27017 Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: t3.utils.connman.cc: Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at t3.utils.connman.c.c.d(MongoDBConnector.java:545)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:179)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:768)
	at com.mongodb.DB.command(DB.java:528)
	at com.mongodb.DB.command(DB.java:544)
	at com.mongodb.DB.command(DB.java:499)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:867)
	at t3.utils.connman.c.c.d(MongoDBConnector.java:424)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-05 13:53:25 [main] t3.utils.connman.ej.a()
ERROR: Update is ProgressUpdate: Connecting to 172.31.33.227:27017 Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: t3.utils.connman.cc: Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at t3.utils.connman.c.c.d(MongoDBConnector.java:545)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:179)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:768)
	at com.mongodb.DB.command(DB.java:528)
	at com.mongodb.DB.command(DB.java:544)
	at com.mongodb.DB.command(DB.java:499)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:867)
	at t3.utils.connman.c.c.d(MongoDBConnector.java:424)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-05 13:54:27 [main] t3.utils.connman.ej.a()
ERROR: Update is ProgressUpdate: Connecting to 172.31.33.227:27017 Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: t3.utils.connman.cc: Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at t3.utils.connman.c.c.d(MongoDBConnector.java:545)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:179)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:768)
	at com.mongodb.DB.command(DB.java:528)
	at com.mongodb.DB.command(DB.java:544)
	at com.mongodb.DB.command(DB.java:499)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:867)
	at t3.utils.connman.c.c.d(MongoDBConnector.java:424)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-05 15:21:30 [main] t3.utils.s.x.akU()
WARNING: Cannot read managed property store from disk: java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at t3.utils.s.x.akU(ManagedPropertyStore.java:228)
	at t3.utils.s.ah.get(PropertyStore.java:248)
	at t3.utils.s.ah.get(PropertyStore.java:245)
	at t3.utils.s.ad.a(PropertyStore.java:64)
	at t3.utils.s.ac.a(PropertyStore.java:245)
	at t3.utils.s.x.read(ManagedPropertyStore.java:224)
	at t3.utils.s.x.a(ManagedPropertyStore.java:128)
	at t3.utils.s.x.lB(ManagedPropertyStore.java:87)
	at t3.utils.s.j.<clinit>(DefaultTrustedPropertyStore.java:16)
	at t3.utils.connman.ed.aP(MongoConnectionInfoRestrictions.java:76)
	at t3.utils.connman.ed.Fm(MongoConnectionInfoRestrictions.java:147)
	at t3.utils.connman.ed.<init>(MongoConnectionInfoRestrictions.java:43)
	at t3.utils.connman.bu.<init>(ConnectionManager.java:89)
	at t3.dataman.mongodb.app.a.<init>(AppController.java:123)
	at t3.dataman.mongodb.app.ae.main(AppRunner.java:84)
	at t3.dataman.mongodb.app.Studio3TApp.main(Studio3TApp.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:53)
2019-03-06 13:36:07 [main] t3.utils.connman.ej.a()
ERROR: Update is ProgressUpdate: Connecting to 172.31.33.227:27017 Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: t3.utils.connman.cc: Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at t3.utils.connman.c.c.d(MongoDBConnector.java:545)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:179)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:768)
	at com.mongodb.DB.command(DB.java:528)
	at com.mongodb.DB.command(DB.java:544)
	at com.mongodb.DB.command(DB.java:499)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:867)
	at t3.utils.connman.c.c.d(MongoDBConnector.java:424)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-06 14:15:33 [3T::Connection Manager Thread] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-06 14:15:40 [3T::Connection Manager Thread] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-07 00:36:16 [3T::AppController::connect] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-07 01:09:09 [3T::Connection Manager Thread] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-08 02:14:16 [3T::Connection Manager Thread] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-08 15:00:42 [main] t3.utils.connman.ej.a()
ERROR: Update is ProgressUpdate: Connecting to 172.31.33.227:27017 Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]: t3.utils.connman.cc: Connection failed.

SERVER [172.31.33.227:27017] (Type: UNKNOWN) 
|_/ Connection error (MongoSocketOpenException): Exception opening socket
|____/ I/O error: connect timed out

Details:
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at t3.utils.connman.c.c.d(MongoDBConnector.java:545)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.31.33.227:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:179)
	at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
	at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:136)
	at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:94)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:249)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:172)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:161)
	at com.mongodb.DB.executeCommand(DB.java:768)
	at com.mongodb.DB.command(DB.java:528)
	at com.mongodb.DB.command(DB.java:544)
	at com.mongodb.DB.command(DB.java:499)
	at t3.utils.connman.c.c.a(MongoDBConnector.java:867)
	at t3.utils.connman.c.c.d(MongoDBConnector.java:424)
	at t3.utils.connman.c.c.c(MongoDBConnector.java:1150)
	at t3.utils.connman.dk.f(DBServerConnector.java:38)
	at t3.utils.connman.bu.c(ConnectionManager.java:996)
	at t3.utils.connman.bu.b(ConnectionManager.java:928)
	at t3.utils.connman.bu.e(ConnectionManager.java:393)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-03-08 15:01:33 [3T::Connection Manager Thread] t3.utils.connman.f.g()
WARNING: consider using isEffectiveVersionOrLater for comparing version against 3.4 or above
2019-03-08 15:02:05 [main] t3.utils.s.v.a()
ERROR: weights of CollectionTab.query_builder_sash.C5E8535B66EFA4E7279B9976DAA56845 not found: java.lang.NullPointerException saved object: null
2019-03-08 21:33:43 [main] t3.utils.s.v.a()
ERROR: weights of CollectionTab.query_builder_sash.C5E8535B66EFA4E7279B9976DAA56845 not found: java.lang.NullPointerException saved object: null
